version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - doxygen
    - graphviz

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt

# Don't build any extra formats
formats: []

# Additional configuration
submodules:
  include: all
  recursive: true
